name: Trigger auto deployment for vascontainerapp2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/vascontainerapp2-AutoDeployTrigger-136dcfee-228b-45f7-a52c-434921417719.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.VASCONTAINERAPP2_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: vasregistry.azurecr.io
          registryUsername: ${{ secrets.VASCONTAINERAPP2_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.VASCONTAINERAPP2_REGISTRY_PASSWORD }}
          containerAppName: vascontainerapp2
          resourceGroup: Web-git
          imageToBuild: vasregistry.azurecr.io/get-net-2:${{ github.sha }}
          
            

     

